version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: db-postgres
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=web_dev
    ports:
      - "5432:5432"
    volumes:
      - ./.data/postgresql/data:/var/lib/postgresql/data
    networks:
      - dev-network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
     - ./.data/pgadmin:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge